language: node_js
node_js: '9'
services:
- postgresql
before_script:
- psql -c 'create database projects_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: qD1xfj9HNgoNtp5zCTIPX1of8kYM8PTRzlwGTsVPG/64ec0mPM6t+68OvAJINAHb1Ich3fw6PltkWgYdgemwM6PEP7+GsNiHfXTM+e5BIHDzN6p1fAJCPHP/NbgvkP1+KYjUbwRXfMLVM55an9nAEPfsZIbhLUIWMDrKK1xA4PSX07NA7vl/HLb7wHLFIczBgr3viWawIT296mgCmHfE3GajBYWtkNdpiJ4BUrSKKjIWsX35cgtfEcRXN67KR2S23iimMsHiz+djx+89kX4ct+ZKLoFcwvvsPoU5aVr6vRzHxsmh5v5VaeAQi1KwfFxKuiJYcRccDlGqHZV33FYo1cvtQyeyYrR8/fCIR2mW52TT7GDfc04jIlaGVXcwUiSmsOHZn2F5x65n8R85+CAY0saJGq3m5J8nOOHWuWjxaSXAMxu5o08Fj9TMDeeTsFFA09ZQJinreSAPjQfDsHeZaN3qWN+3g37JFMderK3d+EKt01ObwOtqCkSycwMMG2pjO36PhhrT/kjaGOvghf1sBJZYdtiZRE7RXuTm+oWoSQHCUMiMqs3837+F0kH2HNLUovgQ79T9RWRauenlsoAjWoBf7s/MrAizFVWhEYLdBWJVX2b3mMzgdH4xYV1dXwTiRMHwIGJE7CdoJwrKeLRhJsR0iIzQZoyYnec+dV8KlPQ=
